import os
from fpdf import FPDF
from typing import Dict, Any

class PDFReport(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.set_text_color(27, 94, 32) # Dark green
        self.cell(0, 10, "Leaf Disease Diagnosis Report", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf(record: Dict[str, Any], output_path: str):
    """Generate a PDF report for a given history record."""
    pdf = PDFReport()
    pdf.add_page()
    
    # Enable auto page break
    pdf.set_auto_page_break(auto=True, margin=15)
    
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    
    # Basic Info
    pdf.cell(0, 8, f"Date: {record.get('timestamp', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Disease Detected: {record.get('disease_name', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Confidence: {record.get('confidence', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    # Helper to print list sections
    def add_section(title, items):
        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(27, 94, 32)
        pdf.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", "", 11)
        pdf.set_text_color(0, 0, 0)
        
        if not items:
            pdf.multi_cell(0, 8, "- None reported.")
        else:
            for item in items:
                # Ensure text is encoded properly or multi_cell handles it
                safe_item = str(item).encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 8, f"- {safe_item}")
        pdf.ln(3)

    add_section("Symptoms", record.get("symptoms", []))
    add_section("Treatment", record.get("treatment", []))
    add_section("Prevention", record.get("prevention", []))
    
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 6, "Disclaimer: This report was generated by AI and does not replace professional agricultural advice.")
    
    pdf.output(output_path)
